### ISSUE TITLE
Could you please provide the experimental dataset?

### ISSUE THREAD

**Issue by longstyl** [AlibakhshiAlireza/AttentionProcess#1]
Without access to the dataset, I am unable to reproduce the experiment. I would greatly appreciate it if you could provide the dataset.

**Comment by AlibakhshiAlireza** [comment]
Hello there. thanks for reaching out. datasets in the paper are publicly available. however, if you want the dataset for the case study, you should email me with further information and agreement not to publicly share it. 
kind regards

**Comment by longstyl** [comment]
Dear Professor Alireza Alibakhshi,

Thank you for your prompt response and for clarifying the availability of
the datasets.

I would like to request the dataset used in the case study. I understand
and agree to the condition regarding not publicly sharing the data. To
provide more context, my research aims to replicate the experimental code
and explore the potential extension of the model in business process
prediction as discussed in the paper. I will ensure that the data is used
solely for this academic purpose and will strictly comply with the relevant
conditions.

Please let me know if you require any further information from my side to
process this request.

Thank you again for your support.

Best regards,
Qian Long

Alireza Alibakhshi ***@***.***> 于2024年12月3日周二 17:19写道：
